### ISSUE TITLE
Exporting model error

### ISSUE THREAD

**Issue by y0un0** [civilServant-666/DeepLab-v3-models-for-waste-material-recognition#1]
Hello,

I try to export your model trained on a MINC and your dataset but i'm stuck with this error:

```
I0216 21:47:06.425489 139870583650176 saver.py:1284] Restoring parameters from /content/drive/MyDrive/models/model.ckpt
2022-02-16 21:47:07.941662: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Out of range: Read less bytes than requested
Traceback (most recent call last):
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: 2 root error(s) found.
  (0) Out of range: Read less bytes than requested
	 [[{{node save/RestoreV2}}]]
	 [[save/RestoreV2/_301]]
  (1) Out of range: Read less bytes than requested
	 [[{{node save/RestoreV2}}]]
0 successful operations.
0 derived errors ignored.
```

How would you export your model? Are the files provided corrupted?

By the way, i'm using tensorflow 1.15.2

**Comment by civilServant-666** [comment]
Hey there, I noticed you just close this post yesterday. Please let me know if you still encounter any problem. 
Best
